config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "ask", to: "questions#ask"
  get "answer", to: "questions#answer"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    @question = params[:question]

    if @question == 'I am going to work'
      @answer = "Great!"
    elsif @question.end_with?('?')
      @answer = 'Silly question, get dressed and go to work!'
    else
      @answer = 'I dont care, get dressed and go to work!'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
  <h1 class="fst-italic text-primary form-label d-grid gap-2 col-6 mx-auto align-middle">Stupid couching</h1>

  <div class="form-label d-grid gap-2 col-6 mx-auto">
    <h3><%= @question %></h3>
    <p><%= @answer %></p>
  </div>
  <button class="btn btn-outline-dark form-label d-grid gap-2 col-6 mx-auto" type="submit">
    <%= link_to "Back", ask_path %>
  </button>

app/views/questions/ask.html.erb
 <body>
  <div container class="m-3" >
    <div class="box">
      <h1 class="fst-italic text-primary d-grid gap-2 col-6 mx-auto">Stupid couching</h1>
      <label for="exampleFormControlInput1" class="form-label d-grid gap-2 col-6 mx-auto">What do you want to ask?</label>
        <form action="/answer" class="form-label d-grid gap-2 col-6 mx-auto" data-turbo="false">
          <input type="text" name="question">
          <input type="submit" value="Ask!">
        </form>
    </div>
  </div>
</body>